/*
 * generated by Xtext 2.29.0
 */
package org.xtext.ide

import com.google.inject.Guice
import org.eclipse.xtext.util.Modules2
import org.xtext.EnvironmentalMonitorDslRuntimeModule
import org.xtext.EnvironmentalMonitorDslStandaloneSetup

/**
 * Initialization support for running Xtext languages as language servers.
 */
class EnvironmentalMonitorDslIdeSetup extends EnvironmentalMonitorDslStandaloneSetup {

	override createInjector() {
		Guice.createInjector(Modules2.mixin(new EnvironmentalMonitorDslRuntimeModule, new EnvironmentalMonitorDslIdeModule))
	}
	
}
