/*
 * generated by Xtext 2.29.0
 */
package org.xtext.ide


/**
 * Use this class to register ide components.
 */
class EnvironmentalMonitorDslIdeModule extends AbstractEnvironmentalMonitorDslIdeModule {
}
