/*
 * generated by Xtext 2.29.0
 */
package org.xtext


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class EnvironmentalMonitorDslStandaloneSetup extends EnvironmentalMonitorDslStandaloneSetupGenerated {

	def static void doSetup() {
		new EnvironmentalMonitorDslStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
